# Generated by Django 4.1 on 2022-08-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('€', 'Euros'), ('$', 'Dollars'), ('H', 'Hryvnias')], default='$', max_length=1),
        ),
    ]
