# Generated by Django 4.1 on 2022-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'Dollars'), ('UAH', 'Hryvnias')], default='USD', max_length=3),
        ),
    ]
