# Generated by Django 4.1 on 2022-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_actor_gender_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Man'), ('Female', 'Woman')], default='Male', max_length=6),
        ),
    ]
