# Generated by Django 4.1 on 2022-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Woman')], default='M', max_length=1),
        ),
    ]
